language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run --source=aslack setup.py test
after_success: coveralls
deploy:
  edge: true
  - provider: pypi
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    on:
      tags: true
  - provider: cloudfoundry
    api: https://api.run.pez.pivotal.io
    username: $CF_USERNAME
    password: $CF_PASSWORD
    organization: pivot-jsharpe
    space: development
    manifest: manifest.yml
    on:
      tags: true
